### ISSUE TITLE
Drop down menu displays incorrectly in Firefox

### ISSUE THREAD

**Issue by dboyer** [azavea/climate-change-lab#289] opened 2017-10-24 18:41 UTC
Tested on production in Firefox on a Mac.

![screen shot 2017-10-24 at 2 40 17 pm](https://user-images.githubusercontent.com/516764/31961672-66488cae-b8c9-11e7-8314-26d3180350c7.png)

**Comment by flibbertigibbet** [comment] 2017-10-24 19:42
See #234

**Comment by CloudNiner** [comment] 2017-11-02 14:52
Closing, duplicate of #234

**Closed by CloudNiner** 2017-11-02 14:52 UTC
Labels: Bug - Low
