### ISSUE TITLE
Charts don't appear on Safari

### ISSUE THREAD

**Issue by fungjj92** [azavea/climate-change-lab#304] opened 2017-11-06 17:39 UTC
<img width="683" alt="screen shot 2017-11-06 at 12 34 56 pm" src="https://user-images.githubusercontent.com/10568752/32455139-60301d48-c2ef-11e7-8b62-adcd1dc31e87.png">

Requests go through and component references update, however. 
Only a problem in Safari, not Chrome nor Firefox. IE not checked yet.

**Comment by flibbertigibbet** [comment] 2017-11-06 17:52
Given the console errors above, may be related to/duplicate of #244.

**Closed** 2017-11-14 16:00 UTC
Labels: in review, Swapped In
