### ISSUE TITLE
New project Models list is empty by default

### ISSUE THREAD

**Issue by rmartz** [azavea/climate-change-lab#331] opened 2018-04-04 15:25 UTC
![screen shot 2018-04-04 at 11 24 14 am](https://user-images.githubusercontent.com/1032849/38317332-cf8bdefe-37fa-11e8-99b0-e215a4caddae.png)
Also prints a console error:
```
ERROR TypeError: Cannot read property 'models' of undefined
    at t.updateButtonText (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at t.updateClimateModels (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e._next (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e.__tryOrUnsub (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e.next (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e._next (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e.next (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e._next (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e.next (vendor.ad958a995e6b6597b56c.bundle.js:1)
    at e._next (vendor.ad958a995e6b6597b56c.bundle.js:1)
```

**Comment by maurizi** [comment] 2018-04-04 15:27
Duplicate of https://github.com/azavea/climate-change-lab/issues/305

**Closed as completed by maurizi** 2018-04-04 15:27 UTC
